# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea45e11b6fac3d5f78aaa27845f4073e99f4d34d4abdd0e6aee07a9ca371f3c1812a226316d972826d9f0d06e8b9ee660a612597327089896e70d75355d26471

test:
  secret_key_base: 7a1dd25399d54c39c1b9623e51562aaa746423ddd1779268c0468ede32dee7e563d736adc268acc72e87f6fdea0e5bce26564fa430fbe89b1fe0ae2a0b749862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
